title: "SUPARNA C"
logo: /assets/images/SUPARNA_portfolio_picture.png 
description: |
  "AI engineer | M.Tech, AI |  
  Image Processing Enthusiast "
show_downloads: false
theme: jekyll-theme-minimal 
